# Generated by Django 5.2.4 on 2025-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(choices=[('Executive', 'Executive'), ('General', 'General')], max_length=50)),
                ('photo', models.ImageField(upload_to='officers_photos/')),
            ],
        ),
    ]
