# Generated by Django 5.2.4 on 2025-09-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='group',
            field=models.CharField(choices=[('Advisor', 'Advisor'), ('Executive', 'Executive'), ('General', 'General')], max_length=50),
        ),
    ]
